version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: videogames_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=videogamesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_development:/var/lib/postgresql

  minio:
    image: minio/minio
    container_name: videogames_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data_development:
  minio_data:
